[package]
name = "hbrs-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hbrs = { path = "./hbrs"}
rand = "0.8"
serde_json = "1.0"